import turtle
# turtle.home()
# turtle.dot()
# turtle.fd(50)
turtle.dot(20, "blue")
turtle.fd(20)
turtle.dot(20, "blue")
turtle.fd(20)
turtle.dot(20, "blue")
turtle.fd(20)
turtle.dot(20, "blue")
turtle.tiltangle(180)
turtle.fd(10)
turtle.dot(20, "blue")
turtle.fd(10)
turtle.dot(20, "blue")
turtle.fd(10)
turtle.dot(20, "blue")

turtle.position()
turtle.heading()
